spring.application.name: uploader-service

spring:
    config:
        import: configserver:http://config-server:8888

    #To connect with cloudnary create account then go to get started click on All SDKs
    # copy java dependency in your pom file.
    # Then go to dashboard create api keys put it here in this file.
    #Create config of cloudnary put the details in them see in config folder.


    # To connect with google cloud create account. Create bucket. Then add permission
    # make it public to all users by going to permission tab grant access write allusers
    # then select role -> clous storage -> storage object viewer.

    # Now connect to bucket go to IAM -> service account -> create account -> select storage = cloud storage -> Storage object admin -> Done
    # Now created account click on 3 dots -> manage keys -> add key -> create new keys -> JSON -> create -> keys will be downloaded. and add those here the keys.
    # Also add google cloud storage maven dependency