spring:
    application:
        # Application name used to find api-gateway.yml
        name: api-gateway

    config:
        # Connect to Config Server container
        import: configserver:http://config-server:8888

