spring:
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.LongSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# point to your kafka folder in my case it is cd C:\kafka.
# create kafka clustor = $KAFKA_CLUSTER_ID = .\bin\windows\kafka-storage.bat random-uuid
# create kafka clustor log(like kafka storage) = .\bin\windows\kafka-storage.bat format --standalone -t $KAFKA_CLUSTER_ID -c .\config\server.properties
# run kafka = .\bin\windows\kafka-server-start.bat .\config\server.properties

# remove clustor logs to create new clustor = Remove-Item -Recurse -Force C:\tmp\kraft-combined-logs
# stop java proces =  Stop-Process -Name java -Force

# run kkraft kafka ui = java "-Dspring.config.additional-location=application-local.yml" "--add-opens=java.rmi/javax.rmi.ssl=ALL-UNNAMED" -jar .\kafbat-ui-v1.0.0.jar