apiVersion: apps/v1
kind: Deployment

metadata:
  name: uploader-service

spec:
  selector:
    matchLabels:
      app: uploader-service

  template:
    metadata:
      labels:
        app: uploader-service

    spec:
      containers:
      - name: uploader-service
        image: jakhar0005/connect-sphere-uploader-service
        imagePullPolicy: Always

        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"

          requests:
            memory: "200Mi"
            cpu: "100m"

        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: connectsphere-config
                key: SPRING_PROFILES_ACTIVE

          - name: CLOUDINARY_CLOUD_NAME
            valueFrom:
              configMapKeyRef:
                name: connectsphere-config
                key: CLOUDINARY_CLOUD_NAME

          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: connectsphere-secret
                key: CLOUDINARY_API_KEY

          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: connectsphere-secret
                key: CLOUDINARY_API_SECRET

                
          - name: GCLOUD_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: connectsphere-secret
                key: GCLOUD_STORAGE_ACCESS_KEY

          - name: GCLOUD_STORAGE_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: connectsphere-secret
                key: GCLOUD_STORAGE_BUCKET_NAME
                
        ports:
        - containerPort: 9070

---
apiVersion: v1
kind: Service

metadata:
  name: uploader-service

spec:
  selector:
    app: uploader-service

  ports:
  - port: 80
    targetPort: 9070