spring.application.name=notification-service

server.servlet.context-path=/notification
server.port = 9050

spring.datasource.url=jdbc:postgresql://localhost:5432/notificationDB
spring.datasource.username=postgres
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

