eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.datasource.url=jdbc:postgresql://${POSTGRES_DB_SERVER}:5432/${DB_NAME}
#postgres,notificationDB
spring.datasource.username=${DB_NAME}
#postgres
spring.datasource.password=${DB_PASSWORD}
#user
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-server=kafka:9092