eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.neo4j.uri=neo4j://${NEO4J_DB_NAME}:7687
# neo4j
spring.neo4j.authentication.username=${NEO4J_DB_NAME}
# neo4j
spring.neo4j.authentication.password=${NEO4J_DB_PASSWORD}
# user@1234

spring.kafka.bootstrap-server=kafka:9092

USER_SERVICE_URI=http://user-service
POST_SERVICE_URI=http://post-service
NOTIFICATION_SERVICE_URI=http://notification-service
CONNECTION_SERVICE_URI=http://connection-service