spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: ${spring.application.name}
            key-deserialize: org.apache.kafka.common.serialization.LongDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json:
                    trusted.packages: com.connectSphere.*